spring:
 application:
  name:customer-service
eureka:
 client:
  serviceUrl:
   defaultZone : http://localhost:9998/eureka/ 
   fetch-registry: true
server:
 port:8763
zuul:
 host:
  socket-timeout-millis : 30000
  

  